version: '3'
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension

  service-a:
    container_name: microservice-a
    build:
      context: .
      dockerfile: Dockerfile.a
    environment:
      - TITLE=Microservice a
      - CONTENT=This is microservice a
      - BACKGROUND_COLOR=green
      - EXTERNAL_CALL_URL=http://service-b:8181
      - EXTERNAL_CALL_METHOD=GET
      - REQUEST_NAME_OTEL=microservice-a-request
      - OTEL_SERVICE_NAME=microservice-a
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8080
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector

  service-b:
    container_name: microservice-b
    build:
      context: .
      dockerfile: Dockerfile.b
    environment:
      - TITLE=Microservice b
      - CONTENT=This is microservice b
      - BACKGROUND_COLOR=blue
      - EXTERNAL_CALL_URL=
      - EXTERNAL_CALL_METHOD=GET
      - REQUEST_NAME_OTEL=microservice-b-request
      - OTEL_SERVICE_NAME=microservice-b
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=:8181
      - WEATHER_KEY=0d02a696df794e82955103053241801
    ports:
      - "8181:8181"
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
      - prometheus
      - otel-collector